MERGE INTO prof_field (id, name_system) VALUES (1, 'SALES');
MERGE INTO prof_field (id, name_system) VALUES (2, 'PRODUCATION');
MERGE INTO prof_field (id, name_system) VALUES (3, 'WORKING_STAFF');
MERGE INTO prof_field (id, name_system) VALUES (4, 'IT');
MERGE INTO prof_field (id, name_system) VALUES (5, 'CARIER_START');
MERGE INTO prof_field (id, name_system) VALUES (6, 'BUILDING');
MERGE INTO prof_field (id, name_system) VALUES (7, 'ADMINISTRATION');
MERGE INTO prof_field (id, name_system) VALUES (8, 'BANKS');
MERGE INTO prof_field (id, name_system) VALUES (9, 'TRANSPORT');
MERGE INTO prof_field (id, name_system) VALUES (10, 'ACCOUNTING');
MERGE INTO prof_field (id, name_system) VALUES (11, 'MARKETING');
MERGE INTO prof_field (id, name_system) VALUES (12, 'TOURISM');
MERGE INTO prof_field (id, name_system) VALUES (13, 'RESTAURANTS');
MERGE INTO prof_field (id, name_system) VALUES (14, 'MEDICINE');
MERGE INTO prof_field (id, name_system) VALUES (15, 'COUNSELING');
MERGE INTO prof_field (id, name_system) VALUES (16, 'CARS');
MERGE INTO prof_field (id, name_system) VALUES (17, 'TOP_MANAGEMENT');
MERGE INTO prof_field (id, name_system) VALUES (18, 'HUMAN_RESOURCES');
MERGE INTO prof_field (id, name_system) VALUES (19, 'SECURITY');
MERGE INTO prof_field (id, name_system) VALUES (20, 'PROCUREMENT');
MERGE INTO prof_field (id, name_system) VALUES (21, 'ART');
MERGE INTO prof_field (id, name_system) VALUES (22, 'MEDIA');
MERGE INTO prof_field (id, name_system) VALUES (23, 'SCIENCE');
MERGE INTO prof_field (id, name_system) VALUES (24, 'EDUCATION');
MERGE INTO prof_field (id, name_system) VALUES (25, 'JURISPRUDENCE');
MERGE INTO prof_field (id, name_system) VALUES (26, 'INSTALLATION');
MERGE INTO prof_field (id, name_system) VALUES (27, 'SPORT');
MERGE INTO prof_field (id, name_system) VALUES (28, 'INSURANCE');
MERGE INTO prof_field (id, name_system) VALUES (29, 'HOME_STAFF');
MERGE INTO prof_field (id, name_system) VALUES (30, 'CIVIL_SERVICE');
MERGE INTO prof_field (id, name_system) VALUES (31, 'MATERIAL_EXTRACTION');

MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (1, 'продажи', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (2, 'производство', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (3, 'раб. персонал', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (4, 'IT, телеком', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (5, 'начало карьеры', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (6, 'строительство', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (7, 'адм. персонал', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (8, 'банки', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (9, 'транспорт', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (10, 'бухгалтерия', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (11, 'маркетинг', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (12, 'туризм', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (13, 'рестораны', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (14, 'медицина', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (15, 'консультирование', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (16, 'авто', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (17, 'топ-менеджмент', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (18, 'управление персоналом', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (19, 'безопасность', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (20, 'закупки', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (21, 'искусство', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (22, 'медиа', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (23, 'наука', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (24, 'образование', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (25, 'юриспруденция', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (26, 'инсталляция', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (27, 'спорт', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (28, 'страхование', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (29, 'дом. персонал', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (30, 'госслужба', 'ru_RU');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (31, 'добыча сырья', 'ru_RU');

MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (1, 'sales', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (2, 'production', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (3, 'working staff', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (4, 'IT', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (5, 'carier start', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (6, 'building', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (7, 'administration', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (8, 'banks', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (9, 'transport', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (10, 'accounting', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (11, 'marketing', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (12, 'tourism', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (13, 'restaurants', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (14, 'medicine', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (15, 'counseling', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (16, 'cars', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (17, 'top management', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (18, 'human resources', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (19, 'security', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (20, 'procurement', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (21, 'art', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (22, 'media', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (23, 'science', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (24, 'education', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (25, 'jurisprudence', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (26, 'installation', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (27, 'sport', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (28, 'insurance', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (29, 'home staff', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (30, 'civil service', 'en');
MERGE INTO prof_field_names_view (prof_field_id, name_view, locale) VALUES (31, 'material extraction', 'en');

MERGE INTO work_type (id, name_system) VALUES (1, 'FULL_DAY');
MERGE INTO work_type (id, name_system) VALUES (2, 'SWIFT_WORK');
MERGE INTO work_type (id, name_system) VALUES (3, 'TOUR_WORK');
MERGE INTO work_type (id, name_system) VALUES (4, 'FLEX_WORK');
MERGE INTO work_type (id, name_system) VALUES (5, 'REMOTE_WORK');

MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (1, 'полный день', 'ru_RU');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (2, 'сменный график', 'ru_RU');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (3, 'вахтовый метод', 'ru_RU');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (4, 'гибкий график', 'ru_RU');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (5, 'удаленная работа', 'ru_RU');

MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (1, 'full day', 'en');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (2, 'shift work', 'en');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (3, 'tour work', 'en');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (4, 'flexible working', 'en');
MERGE INTO work_type_names_view (work_type_id, name_view, locale) VALUES (5, 'remote work', 'en');

MERGE INTO education (id, name_system) VALUES (1, 'WITHOUT');
MERGE INTO education (id, name_system) VALUES (2, 'SECONDARY');
MERGE INTO education (id, name_system) VALUES (3, 'HIGHER');
MERGE INTO education (id, name_system) VALUES (4, 'POSTGRADUATE');

MERGE INTO education_names_view (education_id, name_view, locale) VALUES (1, 'без образования', 'ru_RU');
MERGE INTO education_names_view (education_id, name_view, locale) VALUES (2, 'среднее', 'ru_RU');
MERGE INTO education_names_view (education_id, name_view, locale) VALUES (3, 'высшее', 'ru_RU');
MERGE INTO education_names_view (education_id, name_view, locale) VALUES (4, 'послевузовское', 'ru_RU');

MERGE INTO education_names_view (education_id, name_view, locale) VALUES ('1', 'without education', 'en');
MERGE INTO education_names_view (education_id, name_view, locale) VALUES ('2', 'secondary', 'en');
MERGE INTO education_names_view (education_id, name_view, locale) VALUES ('3', 'heigher', 'en');
MERGE INTO education_names_view (education_id, name_view, locale) VALUES ('4', 'postgraduate', 'en');

MERGE INTO currency (id, name_system) VALUES (1, 'RUB');
MERGE INTO currency (id, name_system) VALUES (2, 'EURO');
MERGE INTO currency (id, name_system) VALUES (3, 'USD');

MERGE INTO currency_names_view (currency_id, name_view, locale) VALUES (1, 'руб.', 'ru_RU');
MERGE INTO currency_names_view (currency_id, name_view, locale) VALUES (2, 'евро', 'ru_RU');
MERGE INTO currency_names_view (currency_id, name_view, locale) VALUES (3, 'долл.', 'ru_RU');

MERGE INTO currency_names_view (currency_id, name_view, locale) VALUES (1, 'rub', 'en');
MERGE INTO currency_names_view (currency_id, name_view, locale) VALUES (2, 'euro', 'en');
MERGE INTO currency_names_view (currency_id, name_view, locale) VALUES (3, 'usd', 'en');

MERGE INTO period (id, name_system) VALUES (1, 'MONTH');
MERGE INTO period (id, name_system) VALUES (2, 'DAY');
MERGE INTO period (id, name_system) VALUES (3, 'HOUR');

MERGE INTO period_names_view (period_id, name_view, locale) VALUES (1, 'в месяц', 'ru_RU');
MERGE INTO period_names_view (period_id, name_view, locale) VALUES (2, 'в день', 'ru_RU');
MERGE INTO period_names_view (period_id, name_view, locale) VALUES (3, 'в час', 'ru_RU');

MERGE INTO period_names_view (period_id, name_view, locale) VALUES (1, 'in month', 'en');
MERGE INTO period_names_view (period_id, name_view, locale) VALUES (2, 'in day', 'en');
MERGE INTO period_names_view (period_id, name_view, locale) VALUES (3, 'in hour', 'en');

MERGE INTO gender (id, name_system) VALUES (1, 'MALE');
MERGE INTO gender (id, name_system) VALUES (2, 'FEMALE');

MERGE INTO gender_names_view (gender_id, name_view, locale) VALUES (1, 'мужской', 'ru_RU');
MERGE INTO gender_names_view (gender_id, name_view, locale) VALUES (2, 'женский', 'ru_RU');

MERGE INTO gender_names_view (gender_id, name_view, locale) VALUES (1, 'male', 'en');
MERGE INTO gender_names_view (gender_id, name_view, locale) VALUES (2, 'female', 'en');

MERGE INTO company_type (id, name_system, financial_type) VALUES (1, 'FULL_PARTNERSHIP', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (2, 'FAITH_PARTNERSHIP', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (3, 'LIMITED_LIABILITY_COMPANY', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (4, 'PUBLIC_JOINT_STOCK_COMPANY', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (5, 'NON_PUBLIC_JOINT_STOCK_COMPANY', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (6, 'PRODUCTION_COOPERATIVE', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (7, 'UNITARY_ENTERPRISE', '0');
MERGE INTO company_type (id, name_system, financial_type) VALUES (8, 'CONSUMER_COOPERATIVE', '1');
MERGE INTO company_type (id, name_system, financial_type) VALUES (9, 'PUBLIC_AND_RELIGIOUS_ASSOCIATIONS', '1');
MERGE INTO company_type (id, name_system, financial_type) VALUES (10, 'FUNDS', '1');
MERGE INTO company_type (id, name_system, financial_type) VALUES (11, 'INSTITUTIONS', '1');
MERGE INTO company_type (id, name_system, financial_type) VALUES (12, 'ASSOCIATIONS', '1');
MERGE INTO company_type (id, name_system, financial_type) VALUES (13, 'UNIONS', '1');

MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (1, 'Полное товарищество', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (2, 'Товарищество на вере', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (3, 'Общество с ограниченной ответственностью', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (4, 'Публичное акционерное общество', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (5, 'Непубличное акционерное общество', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (6, 'Производственный кооператив', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (7, 'Унитарное предприятие', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (8, 'Потребительский кооператив', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (9, 'Общественные и религиозные объединения', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (10, 'Фонды', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (11, 'Учреждения', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (12, 'Ассоциации', 'ru_RU');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (13, 'Союзы', 'ru_RU');

MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (1, 'Full partnership', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (2, 'Faith partnership', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (3, 'Limited liability company', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (4, 'Public joint stock company', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (5, 'Non public joint stock company', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (6, 'Production cooperative', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (7, 'Unitary enterprise', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (8, 'Consumer cooperative', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (9, 'Public and religious associations', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (10, 'Funds', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (11, 'Institutions', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (12, 'Associations', 'en');
MERGE INTO company_type_names_view (company_type_id, name_view, locale) VALUES (13, 'Unions', 'en');

MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (1, 'ПТ', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (2, 'ТВ', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (3, 'ООО', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (4, 'ПАО', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (5, 'НАО', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (6, 'ПРК', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (7, 'УП', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (8, 'ПТК', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (9, 'О', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (10, 'Ф', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (11, 'У', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (12, 'А', 'ru_RU');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (13, 'С', 'ru_RU');

MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (1, 'FullP', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (2, 'FaithP', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (3, 'LLC', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (4, 'PJSC', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (5, 'NPJSC', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (6, 'PC', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (7, 'UE', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (8, 'CC', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (9, 'PRA', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (10, 'F', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (11, 'I', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (12, 'A', 'en');
MERGE INTO company_type_abbreviated_names_view (company_type_id, abbreviated_name_view, locale) VALUES (13, 'U', 'en');

MERGE INTO resume_state (id, name_system) VALUES (1, 'INVITATION_SENT');
MERGE INTO resume_state (id, name_system) VALUES (2, 'TECHNICAL_INTERVIEW');
MERGE INTO resume_state (id, name_system) VALUES (3, 'INTERVIEW');
MERGE INTO resume_state (id, name_system) VALUES (4, 'CUSTOMER_RESUME');
MERGE INTO resume_state (id, name_system) VALUES (5, 'CUSTOMER_INTERVIEW');
MERGE INTO resume_state (id, name_system) VALUES (6, 'OFFER_TO_CANDIDATE');
MERGE INTO resume_state (id, name_system) VALUES (7, 'PROBATION');
MERGE INTO resume_state (id, name_system) VALUES (8, 'HIRED');
MERGE INTO resume_state (id, name_system) VALUES (9, 'REJECTED_BY_RECRUITER');
MERGE INTO resume_state (id, name_system) VALUES (10, 'REJECTED_BY_CUSTOMER');
MERGE INTO resume_state (id, name_system) VALUES (11, 'RESERVE');

MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (1, 'Отправлено приглашение', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (2, 'Тех. интервью', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (3, 'Интервью', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (4, 'Резюме у заказчика', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (5, 'Интервью с заказчиком', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (6, 'Предложение кандидату', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (7, 'Испытательный срок', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (8, 'Принят на работу', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (9, 'Отклонен рекрутером', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (10, 'Отклонен заказчиком', 'ru_RU');
MERGE INTO resume_state_names_view (resume_state_id, name_view, locale) VALUES (11, 'Резерв', 'ru_RU');